[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "mongorun"
dynamic = ["version", "readme", "dependencies"]
description = "A utility to quickly set up complex MongoDB test environments on a local machine "
authors = [
    {name = "Samantha Rapp", email = "samantha.rapp@mongodb.com"},
  ]
license = "Apache-2.0"
classifiers= [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Topic :: Database',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11'
  ]
keywords = ['MongoDB', 'testing']
requires-python = ">=3.8"

[project.scripts]
mrun = "mrun.mrun:main"

[project.urls]
Documentation = "https://mongodb.github.io/mongorun/"
Repository = "https://github.com/mongodb/mongorun"
Changelog = "https://github.com/mongodb/mongorun/blob/main/CHANGES.rst"

[tool.setuptools]
include-package-data = false

[tool.setuptools.dynamic]
version = {attr = "mrun.util.version.__version__"}
readme = {file = "README.rst"}
dependencies = {file = "requirements.txt"}

[tool.setuptools.packages.find]
exclude = ["mrun.test", "mrun.test.*"]